// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpgtlQCKnsN2v7hal0uX-8uS5cYeQHUQ',
    appId: '1:233110171830:web:c9e2f52df4d4bf5f317617',
    messagingSenderId: '233110171830',
    projectId: 'books-app-7511a',
    authDomain: 'books-app-7511a.firebaseapp.com',
    storageBucket: 'books-app-7511a.appspot.com',
    measurementId: 'G-VP8Z9ZB2MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiY0Y10NlDMkIeL3HytfC2iOEwfAh4M6g',
    appId: '1:233110171830:android:ce0e5536f9df3625317617',
    messagingSenderId: '233110171830',
    projectId: 'books-app-7511a',
    storageBucket: 'books-app-7511a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2R6ipyLN0_th5hYwnF5MYSqwKVJ1gDo4',
    appId: '1:233110171830:ios:be3b581865514572317617',
    messagingSenderId: '233110171830',
    projectId: 'books-app-7511a',
    storageBucket: 'books-app-7511a.appspot.com',
    iosBundleId: 'com.example.testApp',
  );
}
